[package]
name = "linkerd-signal"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
tokio = { path = "../../crates/tokio/tokio", features = ["macros", "signal"] }
tracing = "0.1"
